BaSP-MR-09: Class - delete and update
BaSP-m2023/yankee-megarocket-server pull request #40
Opened 2023-05-15 14:04 UTC by JuanIgnacioSobral

2023-05-15 18:00 UTC, AleMac17 requested changes

2023-05-15 18:00 UTC, AleMac17 commented on src/validations/classes.js
> +    day: Joi.string().lowercase().valid('monday', 'tuesday', 'wednesday', 'thursday', 'friday').required(),
No need to use lowercase()
Please remove it from the validation

2023-05-15 18:00 UTC, AleMac17 commented on src/validations/classes.js
> +const validateUpdate = (req, res, next) => {
It is not necessary to do two validations since the put method can use the same validation as the post one. The put method needs to have required()

2023-05-15 18:00 UTC, AleMac17 commented on src/routes/classes.js
> +  .put('/:id', validations.validateUpdate, classesController.updateClass)
Use the validation from the post method

2023-05-15 21:00 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +const validateUpdate = (req, res, next) => {
I can delete the put method validation altogether, since I'm not the one developing. Would that be ok?

2023-05-15 21:01 UTC, JuanIgnacioSobral commented on src/routes/classes.js
> +  .put('/:id', validations.validateUpdate, classesController.updateClass)
Same as last comment:

is if ok if I delete the put method validation altogether, since I'm not the one developing it?

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +    day: Joi.string().lowercase().valid('monday', 'tuesday', 'wednesday', 'thursday', 'friday').required(),
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +    day: Joi.string().lowercase().valid('monday', 'tuesday', 'wednesday', 'thursday', 'friday'),
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +    trainerId: Joi.string().alphanum().lowercase(),
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +    trainerId: Joi.string().alphanum().lowercase().required(),
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/models/Class.js
> +      lowercase: true,
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/models/Class.js
> +      lowercase: true,
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/models/Class.js
> +      lowercase: true,
Removed lowercase requeriment

2023-05-15 21:02 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +    activityId: Joi.string().alphanum().lowercase().required(),
Removed lowercase requeriment

2023-05-15 21:20 UTC, JuanIgnacioSobral commented on src/validations/classes.js
> +const validateUpdate = (req, res, next) => {
Applied the same validation as post method

2023-05-15 21:20 UTC, JuanIgnacioSobral commented on src/routes/classes.js
> +  .put('/:id', validations.validateUpdate, classesController.updateClass)
Applied the same validation as post method

2023-05-15 22:18 UTC, AleMac17 commented on src/routes/classes.js
> +  .put('/:id', validations.validateUpdate, classesController.updateClass)
You change the validation in the put method?
.put('/:id', validations.validateCreation,

2023-05-16 01:46 UTC, JuanIgnacioSobral commented on src/routes/classes.js
> +  .put('/:id', validations.validateUpdate, classesController.updateClass)
Yes! The function is named validateUpdate, but it has the same contents as validateCreation.

2023-05-16 23:53 UTC, AleMac17 approved these changes

2023-05-17 01:05 UTC, nicolasblasco approved these changes

2023-05-18 01:37 UTC, LucianoAlarcon approved these changes

2023-05-18 01:38 UTC, merged