BaSP-MR-8: Classes Get, Get by ID & Create
BaSP-m2023/yankee-megarocket-server pull request #42
Opened 2023-05-15 14:48 UTC by keiler-art

Created schema, validations and controllers (get, get by id and create) for classes. Also added the corresponding routes.

2023-05-15 17:31 UTC, AleMac17 requested changes

2023-05-15 17:31 UTC, AleMac17 commented on src/controllers/classes.js
> +      message: 'Server error',
In the message of the catch return, we need to put an error.
for example "message: error,"

2023-05-15 17:31 UTC, AleMac17 commented on src/controllers/classes.js
> +    const classes = await Class.find({});
Inside the find method, we only use (); without braces.
for example : "Class.find();"

2023-05-15 23:25 UTC, keiler-art commented on src/controllers/classes.js
> +    const classes = await Class.find({});
Done!

2023-05-15 23:26 UTC, keiler-art commented on src/controllers/classes.js
> +      message: 'Server error',
Already done.

2023-05-15 23:42 UTC, LucianoAlarcon approved these changes

2023-05-16 00:21 UTC, nicolasblasco approved these changes

2023-05-16 00:27 UTC, merged