BaSP-MR-05: Members Put and Delete
BaSP-m2023/yankee-megarocket-server pull request #43
Opened 2023-05-15 15:59 UTC by jramire5

2023-05-15 17:16 UTC, AleMac17 requested changes

2023-05-15 17:16 UTC, AleMac17 commented on src/controllers/members.js
> +export const editMember = async (req, res) => {
You have to adapt the code to work with id as a parameter

2023-05-15 20:22 UTC, nicolasblasco requested changes

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +export const editMember = async (req, res) => {
We should rename the controller to `updateMember`

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    } = req.body;
There is no need to restructure the body. We can directly do `const { body } = req` and use the `body` instead of the destructured object

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +      return res.status(404).json({
The status code is 400 for Bad Request

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    }
There is no need to find the member by id and check if it exists because we are already are doing that in the findByIdAndUpdate method

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    );
We could use `body` instead of the destructured object.
We should save the result in a variable `const updatedMember` and then check if it returns empty to return an error. If not, we return the member updated

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +      return res.status(404).json({
The status code is 400 for Bad Request

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    }
There is no need to find the member by id and check if it exists because we are already are doing that in the findByIdAndDelete method

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    await Member.findByIdAndDelete(id);
We should save the result in a variable `const deletedMember` and then check if it returns empty to return an error. If not, we return the member deleted.

2023-05-15 20:22 UTC, nicolasblasco commented on src/controllers/members.js
> +    return res.status(201).json({
The status code should be 200

2023-05-16 01:43 UTC, nicolasblasco approved these changes

2023-05-16 01:44 UTC, AleMac17 approved these changes

2023-05-16 01:57 UTC, merged