Feature/mr 3/admins put and delete
BaSP-m2023/yankee-megarocket-server pull request #46
Opened 2023-05-15 19:09 UTC by Roberto-Orazi

I finish everyting and try it in postman and works correctly

2023-05-15 19:35 UTC, AleMac17 requested changes

2023-05-15 19:35 UTC, AleMac17 commented on src/models/Admin.js
> +      minLength: 7,
minLength is not a validator for numbers in mongoose
you have to use min

2023-05-15 19:35 UTC, AleMac17 commented on src/models/Admin.js
> +      maxLength: 8,
maxLength is not a validator for numbers in mongoose
You have to use max

2023-05-15 19:35 UTC, AleMac17 commented on src/models/Admin.js
> +      minLength: 10,
minLength is not a validator for numbers in mongoose
You have to use min

2023-05-15 19:35 UTC, AleMac17 commented on src/validations/admins.js
> +    dni: Joi.number().min(10000000).max(99999999),
In the schema you put this 
` dni: {
      type: Number,
      required: true,
      minLength: 7,
      maxLength: 8,
    },`
    In the dni validation here you put numbers with 8 digits but in the schema you put 7 digits

2023-05-15 22:47 UTC, AleMac17 requested changes

2023-05-15 22:47 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 6,
In Mongoose min in numbers its not the same as minlength. You have to put the exact min number
example `min: 100000`

2023-05-15 22:47 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 10,
In Mongoose min in numbers its not the same as minlength. You have to put the exact min number
example `min: 1000000000`

2023-05-15 22:47 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 7,
In Mongoose min in numbers its not the same as minlength. You have to put the exact min number
example `min: 1000000`

2023-05-15 22:47 UTC, AleMac17 commented on src/models/Admin.js
> +      max: 8,
In Mongoose max in numbers its not the same as maxlength. You have to put the exact max number
example `max: 99999999`

2023-05-15 22:48 UTC, AleMac17 requested changes

2023-05-15 22:48 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 3,
For strings you need to use minLength and maxLength

2023-05-15 22:48 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 3,
For strings you need to use minLength and maxLength

2023-05-16 15:13 UTC, AleMac17 requested changes

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +      message: 'Server error.',
In the message of the catch return, we need to put an error.
for example ` message: error,`

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +        error: false,
Status 404 is considered an error.
should be: `error: true,`

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +        error: false,
Status 404 is considered an error.
should be: `error: true,`

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +      error,
The: true is missing after the error.
should be: `error: true,`

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +      data: error,
In data we are using one of these.  data: {} || [] || undefined

2023-05-16 15:13 UTC, AleMac17 commented on src/controllers/admins.js
> +      message: 'Server error',
In the message of the catch return, we need to put an error.
for example  `message: error,`

2023-05-16 15:23 UTC, AleMac17 requested changes

2023-05-16 15:23 UTC, AleMac17 commented on src/controllers/admins.js
> +        data: [{}],
In data we are using only one of these: data: {} || [] || undefined

2023-05-16 15:23 UTC, AleMac17 commented on src/controllers/admins.js
> +        data: [{}],
In data we are using only one of these: data: {} || [] || undefined

2023-05-16 22:47 UTC, AleMac17 approved these changes

2023-05-16 23:28 UTC, nicolasblasco approved these changes

2023-05-17 00:11 UTC, merged