BaSP-MR-7: TRAINERS - Put and Delete
BaSP-m2023/yankee-megarocket-server pull request #48
Opened 2023-05-15 21:46 UTC by MatiasSauvanet

-Added put and delete for trainers
-Added postman collection Data

2023-05-15 22:07 UTC, AleMac17 requested changes

2023-05-15 22:07 UTC, AleMac17 commented on src/controllers/trainers.js
> +      message: 'Server error',
In the message of the catch return, we need to put an error.
for example "message: error,"

2023-05-15 22:07 UTC, AleMac17 commented on src/controllers/trainers.js
> +      error,
The: true is missing after the error.
should be: "error: true;" like line 17.

2023-05-16 15:36 UTC, AleMac17 approved these changes

2023-05-16 18:50 UTC, AleMac17 approved these changes

2023-05-17 01:04 UTC, nicolasblasco approved these changes

2023-05-17 16:36 UTC, LucianoAlarcon approved these changes

2023-05-17 16:45 UTC, merged