BaSP-MR-2: ADMINS - get, getById and create
BaSP-m2023/yankee-megarocket-server pull request #49
Opened 2023-05-15 22:11 UTC by Franro212

2023-05-15 22:35 UTC, AleMac17 requested changes

2023-05-15 22:35 UTC, AleMac17 commented on src/models/Admin.js
> +      min: 7,
In mongoose min in numbers its not the same as minlength. You has to put the exact max number
`min: 1000000`

2023-05-15 22:41 UTC, AleMac17 requested changes

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      message: 'Error! getting administrators.',
In the message of the catch return, we need to put an error.
for example `message: error,`

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      error,
The: true is missing after the error.
should be: `error: true,` like line 29.

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      error,
The: true is missing after the error.
should be: `error: true,` like line 29.

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      message: 'Error! getting the administrator.',
In the message of the catch return, we need to put an error.
for example `message: error,`

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      message: 'Error! Failed to create the administrator.',
In the message of the catch return, we need to put an error.
for example `message: error,`

2023-05-15 22:41 UTC, AleMac17 commented on src/controllers/admins.js
> +      error,
The: true is missing after the error.
should be: `error: true,` like line 29.

2023-05-16 15:33 UTC, AleMac17 requested changes

2023-05-16 15:33 UTC, AleMac17 commented on src/controllers/admins.js
> +      return res.status(404).json({
Status 404 is for requests that the requested resource does not exist.
In this case, the object is not valid, the appropriate thing would be to use status 400.

2023-05-16 18:52 UTC, AleMac17 requested changes

2023-05-16 18:52 UTC, AleMac17 commented on src/controllers/admins.js
> +        error: false,
Status 404 is considered an error.
should be: `error: true,`

2023-05-16 22:43 UTC, AleMac17 approved these changes

2023-05-16 22:43 UTC, AleMac17 approved these changes

2023-05-17 01:49 UTC, nicolasblasco approved these changes

2023-05-17 02:53 UTC, merged