BaSP-MR-14: SUPERADMINS - get, getById and create
BaSP-m2023/yankee-megarocket-server pull request #50
Opened 2023-05-15 22:19 UTC by araefe1992

2023-05-15 22:28 UTC, AleMac17 requested changes

2023-05-15 22:28 UTC, AleMac17 commented on src/controllers/super-admins.js
> +    const {
There is no need to restructure the body. We can directly do const { body } = req and use the body instead of the destructured object

2023-05-15 22:28 UTC, AleMac17 commented on src/controllers/super-admins.js
> +    const trainer = await SuperAdmins.create({
This is superAdmin no trainer.
`const superAdmin`

2023-05-15 22:28 UTC, AleMac17 commented on src/controllers/super-admins.js
> +      data: trainer,
This is superAdmin no trainer.

2023-05-16 00:58 UTC, nicolasblasco approved these changes

2023-05-16 00:59 UTC, AleMac17 approved these changes

2023-05-16 01:21 UTC, merged