BaSP-MR-15: SuperAdmin Put and Delete
BaSP-m2023/yankee-megarocket-server pull request #51
Opened 2023-05-16 02:53 UTC by jramire5

2023-05-16 14:34 UTC, AleMac17 approved these changes

2023-05-16 14:40 UTC, AleMac17 requested changes

2023-05-16 14:45 UTC, AleMac17 requested changes

2023-05-16 14:45 UTC, AleMac17 commented on src/controllers/super-admins.js
> +    return res.status(201).json({
Status 201 is for requests that were made successfully and created an item.
In this case, the appropriate thing would be to use status 200

2023-05-17 01:45 UTC, nicolasblasco approved these changes

2023-05-17 01:46 UTC, merged