MR-23: admins test: get-getById-post. First commit
BaSP-m2023/yankee-megarocket-server pull request #64
Opened 2023-05-21 20:34 UTC by JuanIgnacioSobral

I included the delete test since I was unaware that it should go on a differente PR. Please ignore it.

2023-05-21 21:21 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +describe('DELETE /api/admins', () => {
This method belongs to another PR

2023-05-21 21:21 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +describe('POST /api/admins', () => {
There should be a POST error test

2023-05-21 22:19 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    const response = await request(app).get('/api/admin').send();
This test is going to pass but is not reflective of the actual mistake, try console login the response to see the error message to double check

2023-05-21 22:19 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    const response = await request(app).get('/api/admin').send();
This test is going to pass but is not reflective of the actual mistake, try console login the response to see the error message to double check

2023-05-22 01:43 UTC, nicolasblasco requested changes
We should add a description to our pull request

2023-05-22 01:43 UTC, nicolasblasco commented on src/tests/admins.test.js
> +    expect(response.status).toBe(200);
Don't you think we can test the body of the response? We can test the message, data, and error of the body of the response.

We should do this for all of our tests.

2023-05-22 01:43 UTC, nicolasblasco commented on src/tests/admins.test.js
> +    expect(response.error).toBeFalsy();
I don't think it's necessary to test the error of the response because if we test our response.body we are already testing that error.

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(200);
Remember to add the expects for the error, data and message

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(200);
Remember to add the expects for the error, data and message

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(404);
Remember to add the expects for the error, data and message

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
add the expect for the error to be true

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(201);
Remember to add the expects for the error, data and message

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(400);
Remember to add the expects for the error, data and message

2023-05-22 18:20 UTC, JuanManuel-Blois commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
add the expect for the error to be true

2023-05-23 23:56 UTC, LucianoAlarcon approved these changes

2023-05-23 23:56 UTC, JuanManuel-Blois approved these changes

2023-05-23 23:57 UTC, nicolasblasco approved these changes

2023-05-24 00:02 UTC, merged