BaSP-MR-35: TRAINERS TEST- get, getById and create
BaSP-m2023/yankee-megarocket-server pull request #65
Opened 2023-05-21 21:59 UTC by ticilicarzze

2023-05-21 22:40 UTC, JuanManuel-Blois commented on src/tests/trainers.test.js
> +    const response = await request(app).get('/api/trainersadasd').send();
This test is going to pass as a false positive but is not reflective of the actual mistake, try console login the response to see the error message to double check

2023-05-21 22:40 UTC, JuanManuel-Blois commented on src/tests/trainers.test.js
> +    const response = await request(app).get('/api/trainer/64693b1d0b3782bf437c3821').send();
This test is going to pass as a false positive but is not reflective of the actual mistake, try console login the response to see the error message to double check

2023-05-21 22:40 UTC, JuanManuel-Blois commented on src/tests/trainers.test.js
> +    const response = await request(app).post('/api/trainer').send();
This test is going to pass as a false positive but is not reflective of the actual mistake, try console login the response to see the error message to double check

2023-05-21 22:46 UTC, JuanManuel-Blois commented
You need to restore the deleted files to avoid conflicts with future PR's.

2023-05-22 01:40 UTC, nicolasblasco requested changes
We should add a description to our pull request

2023-05-22 01:40 UTC, nicolasblasco commented on src/tests/trainers.test.js
> +    expect(response.status).toBe(200);
Don't you think we can test the body of the response? We can test the message, data, and error of the body of the response.

We should do this for all of our tests.

2023-05-22 01:40 UTC, nicolasblasco commented on src/tests/trainers.test.js
> +    const response = await request(app).get('/api/trainers/64693b1d0b3782bf437c3826').send();
What happens if we change the trainer ID in the seed file? I think we should capture the id of the first trainer from the seed into a variable. Then we can use it for our tests.

2023-05-24 01:13 UTC, LucianoAlarcon approved these changes

2023-05-24 01:26 UTC, nicolasblasco approved these changes

2023-05-24 01:34 UTC, merged