Feature/mr 32/subscription test update and delete
BaSP-m2023/yankee-megarocket-server pull request #66
Opened 2023-05-22 00:42 UTC by JuanManuel-Blois

Added the delete and put method tests, for succes code 200 and error code 400

2023-05-22 01:37 UTC, nicolasblasco requested changes

2023-05-22 01:37 UTC, nicolasblasco commented on src/tests/subscriptions.test.js
> +    const response = await request(app).put('/api/subscriptions/64694cb404b48dafdecfa44a').send({
What happens if we change the subscription ID in the seed file? I think we should capture the id of the first subscription from the seed into a variable. 

We should use this variable throughout our tests.

2023-05-22 01:37 UTC, nicolasblasco commented on src/tests/subscriptions.test.js
> +    expect(response.status).toBe(200);
Don't you think we can test the body of the response? We can test the message, data, and error of the body of the response.

We should do this for all of our tests.

2023-05-22 01:37 UTC, nicolasblasco commented on src/tests/subscriptions.test.js
> +    });
I think we should move this data into a variable called `mockedSubscription` so we can use it thought our tests

2023-05-23 02:23 UTC, LucianoAlarcon requested changes

2023-05-23 02:23 UTC, LucianoAlarcon commented on src/tests/subscriptions.test.js
> +    expect(response.body.data).toBeDefined();
Can toy change `.toBeDefined()` to `toEqual({})`

2023-05-23 02:23 UTC, LucianoAlarcon commented on src/tests/subscriptions.test.js
> +    expect(response.body.data).toBeDefined();
Can toy change `.toBeDefined()` to `toEqual({})`

2023-05-23 17:46 UTC, nicolasblasco approved these changes

2023-05-23 17:47 UTC, merged