BaSP-MR-28: CLASS TEST - update and delete
BaSP-m2023/yankee-megarocket-server pull request #67
Opened 2023-05-22 00:59 UTC by araefe1992

2023-05-22 01:32 UTC, nicolasblasco requested changes
We should also add a description to our pull request

2023-05-22 01:32 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    const response = await request(app).put('/api/classes/64693c420b3782bf437c382f').send(mockClass);
What happens if we change the class ID in the seed file? I think we should capture the id of the first class from the seed into a variable. Then we can use it for our tests.

2023-05-22 01:32 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    expect(response.status).toBe(200);
Don't you think we can test the body of the response? We can test the message, data, and error of the body of the response. 

We should do this for all of our tests.

2023-05-22 01:32 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    const response = await request(app).put('/api/classes/64693c420b3782bf437c382r').send(mockClass);
I think we could create a variable called `mockedInvalidId` and use it as the parameter of the route

2023-05-22 02:17 UTC, JuanManuel-Blois commented on src/tests/classes.test.js
> +    const response = await request(app).delete('/api/classes/64693c420b3782bf437c382f').send(mockClass);
The mockClass is not necessary in the .send(), at the same time you should put it in the URL instead of the hard coded id

2023-05-22 02:17 UTC, JuanManuel-Blois commented on src/tests/classes.test.js
> +    const response = await request(app).delete('/api/classes/64693c420b3782bf437c3829').send(mockClass);
The mockClass is not necessary in the .send(), at the same time you should put the invalidMockClass in the URL instead of the hard coded id

2023-05-22 20:33 UTC, araefe1992 commented
I only modified the seeds and the tests files, this files are because i pulled from an old commit and they just appeared in my code:
-   src/controllers/classes.js
- src/controllers/subscriptions.js
- src/models/Class.js
- src/models/Subscription.js
- src/validations/subscriptions.js

2023-05-22 23:30 UTC, JuanManuel-Blois commented on src/tests/classes.test.js
> +
We should have a case where the format of the id is correct but doesnt exist

2023-05-23 00:02 UTC, JuanManuel-Blois approved these changes

2023-05-23 01:22 UTC, nicolasblasco requested changes

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    expect(response.body.message).toBe('This is not a valid object Id');
We should also test the data of the body is empty. We could use to `toBeEqual({})`

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    expect(response.body.message).toBe('This is not a valid object Id');
We should also test the data of the body is empty. We could use to `toBeEqual({})`

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    expect(response.body.message).toBe('This is not a valid object Id');
We should also test the data of the body is empty. We could use to `toBeEqual({})`

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +    expect(response.body.message).toBe('This is not a valid object Id');
We should also test the data of the body is empty. We could use to `toBeEqual({})`

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +});
We could also test the response.body when there is a server error

2023-05-23 01:22 UTC, nicolasblasco commented on src/tests/classes.test.js
> +  });
We could also test the response.body when there is a server error

2023-05-23 01:49 UTC, nicolasblasco approved these changes

2023-05-23 01:49 UTC, merged