BaSP-MR-29: MEMBER TEST - get, getById and create
BaSP-m2023/yankee-megarocket-server pull request #68
Opened 2023-05-22 02:49 UTC by AleMac17

In the next commit, i will add the test for status 500.

Seed
Create one member in member.js seed for the unit tests

Unit Test
Create test for get method.
Create test for getById method.
Create test for create method.

2023-05-22 02:54 UTC, AleMac17 commented on src/tests/members.test.js
> +  test('should return status 2010', async () => {
This is status 201

2023-05-22 17:55 UTC, JuanManuel-Blois commented on src/tests/members.test.js
> +    expect(response.body.data.length).toBe(undefined);
We also need to check the response message

2023-05-22 17:55 UTC, JuanManuel-Blois commented on src/tests/members.test.js
> +    expect(response.body.data.length).toBe(undefined);
We also need to check the response message

2023-05-23 00:15 UTC, JuanManuel-Blois approved these changes

2023-05-23 01:28 UTC, nicolasblasco requested changes

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.data.length).toBe(undefined);
Should we test data.length when the data is an object? Maybe we could do
`expect(response.body.data).toBeEqual({});`

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.error).toBeTruthy();
We should also test the message and data of the body

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.data.length).toBe(undefined);
Same as above

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.data.length).toBe(undefined);
Same as above

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.error).toBeTruthy();
We should also test the message and data of the body

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.message).toBe('Member could not be created!');
We should also test the data of the body

2023-05-23 01:28 UTC, nicolasblasco commented on src/tests/members.test.js
> +    expect(response.body.error).toBeTruthy();
We should also test the message and data of the body

2023-05-23 23:21 UTC, LucianoAlarcon approved these changes

2023-05-23 23:23 UTC, nicolasblasco approved these changes

2023-05-23 23:23 UTC, merged