BaSP-MR-33: SUPERADMIN TEST - Get, Get by Id & Create
BaSP-m2023/yankee-megarocket-server pull request #70
Opened 2023-05-22 15:55 UTC by keiler-art

2023-05-22 18:05 UTC, JuanManuel-Blois commented on src/tests/super-admins.test.js
> +    const response = await request(app).get('/api/super-admins/635316fe464e1ad6227622e5').send();
Create a variable called InvalidSuperAdminMockup with this invalid ID to check it

2023-05-22 18:08 UTC, JuanManuel-Blois commented on src/tests/super-admins.test.js
> +    const response = await request(app).get('/api/super-admins/635316fe464e1ad6227622e4').send();
replace this Id with the variable where you call the seed id

2023-05-23 01:39 UTC, keiler-art commented on src/tests/super-admins.test.js
> +    const response = await request(app).get('/api/super-admins/635316fe464e1ad6227622e4').send();
Done!

2023-05-23 02:14 UTC, nicolasblasco requested changes
Please add a description to our pull request

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +};
I think we shouldn't use an object for the id. We could directly do this `const mockWrongId = '635316fe464e1ad6227622e5'`

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +};
I think we shouldn't use an object for the id. We could directly do this `const mockWrongId = '635316fe464e1ad6227622e5'`

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +    expect(response.body.data).toBeDefined();
We could test the data.length `expect(response.body.data.length).toBeGreaterThan(0)`

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +    expect(response.error).toBeTruthy();
We should test the message, data and error of the body of the response

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +    expect(response.body.data.length).toBe(undefined);
Are we sure that we should test the length of an object? I think we could test the data like this `expect(response.body.data).toBeEqual({})`

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +  });
We should test the message, data and error of the body of the response

2023-05-23 02:14 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +    expect(response.error).toBeTruthy();
We should test the message, data and error of the body of the response

2023-05-24 01:02 UTC, merged