BaSP-MR-34: Super admin Test - Put and delete
BaSP-m2023/yankee-megarocket-server pull request #71
Opened 2023-05-22 22:37 UTC by MatiasSauvanet

2023-05-22 22:58 UTC, AleMac17 commented on src/tests/super-admins.test.js
> +  test('Should not be found and delete an super admin, return error 400', async () => {
Small grammatical comment
Should be `delete a super admin`

2023-05-22 23:01 UTC, AleMac17 commented on src/tests/super-admins.test.js
> +describe('DELETE /api/super-admin', () => {
The endpoint is super-admins.

2023-05-22 23:03 UTC, AleMac17 commented on src/tests/super-admins.test.js
> +describe('PUT /api/super-admin', () => {
In the describe we should put the method and the endpoint. In this case, the endpoint is super-admin**s**

2023-05-22 23:16 UTC, JuanManuel-Blois commented on src/tests/super-admins.test.js
> +  });
We could add a test where we check that the id that was given is valid or not, for an example what if we pass an id composed as "123123asdasd", this would be a new error to check for

2023-05-22 23:39 UTC, JuanManuel-Blois commented on src/tests/super-admins.test.js
> +  });
Another test we are missing is in the case that we have no superadmins created

2023-05-23 00:18 UTC, JuanManuel-Blois approved these changes

2023-05-23 01:32 UTC, nicolasblasco requested changes

2023-05-23 01:32 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +  });
We could also test the message, data and error of the body of our response

2023-05-23 01:32 UTC, nicolasblasco commented on src/tests/super-admins.test.js
> +  });
We could also test the message, data and error of the body of our response

2023-05-23 01:32 UTC, nicolasblasco commented
We should also add a description to our pull request

2023-05-23 02:33 UTC, nicolasblasco approved these changes

2023-05-23 03:00 UTC, merged