Feature/mr 26/activities test update and delete
BaSP-m2023/yankee-megarocket-server pull request #73
Opened 2023-05-22 23:26 UTC by Roberto-Orazi

In this branch i do the test for the activities feature on the update and delete.

2023-05-23 00:15 UTC, AleMac17 requested changes

2023-05-23 00:15 UTC, AleMac17 commented on jest.setup.js
> +}, 30000);
We shouldn't add code in the setup environment

2023-05-23 00:15 UTC, AleMac17 commented on src/tests/activities.test.js
> +  test('It should send error 400 because the IId is invalid', async () => {
Typo error `the **I**Id is`

2023-05-23 00:27 UTC, AleMac17 requested changes

2023-05-23 00:27 UTC, AleMac17 commented on src/tests/activities.test.js
> +    expect(response.body).toEqual(expect.arrayContaining(activitySeed));
Don't you think we can test the body of the response? We can test the message, data, and error of the body of the response.

We should do this for all of our tests.

2023-05-23 16:04 UTC, JuanManuel-Blois commented on src/tests/activities.test.js
> +/* eslint-disable no-underscore-dangle */
GENERAL: The get, get by id and post methods are present when they belong to another branch, this might be because you created the branch coming out of the previous branch instead of the master, make sure that they cause no conflicts with your other PR

2023-05-23 16:05 UTC, JuanManuel-Blois commented on src/tests/activities.test.js
> +});
up to this point please check the previous PR for corrections

2023-05-23 16:05 UTC, JuanManuel-Blois commented on src/tests/activities.test.js
> +    expect(response.status).toBe(500);
we should add expects for the error, data and message of the body in this test

2023-05-23 16:06 UTC, JuanManuel-Blois commented on src/tests/activities.test.js
> +    expect(response.status).toBe(500);
we should add expects for the error, data and message of the body in this test

2023-05-23 17:37 UTC, JuanManuel-Blois commented on src/tests/activities.test.js
> +  test('It should send error 400 because the IId is invalid', async () => {
"IId" has an extra "I" still make sure to correct this

2023-05-24 01:01 UTC, nicolasblasco approved these changes

2023-05-24 01:15 UTC, LucianoAlarcon approved these changes

2023-05-24 01:15 UTC, merged